export const CHANGE_ROOT = 'CHANGE_ROOT'
export const NEW_GEO_WATCH = 'NEW_GEO_WATCH'
export const NEW_LOCATION = 'NEW_LOCATION'
export const RIDE_SAVED = 'RIDE_SAVED'
export const RECEIVE_JWT = 'RECEIVE_JWT'
export const RIDES_FETCHED = 'RIDES_FETCHED'
