# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'equesteo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for equesteo

  # Required by RNFirebase
  pod 'Firebase/Core', '~> 5.3.0'
  pod 'Firebase/Messaging'
  pod 'RNFirebase', :path => '../node_modules/react-native-firebase/ios'
  pod 'Mixpanel'

  # from https://github.com/ivpusic/react-native-image-crop-picker
  rn_path = '../node_modules/react-native'

  # from https://github.com/oblador/react-native-vector-icons
  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'
  
  pod 'RNSVG', :path => '../node_modules/react-native-svg'

  pod 'yoga', path: "#{rn_path}/ReactCommon/yoga/yoga.podspec"
  pod 'React', path: rn_path, subspecs: [
    'Core',
    'CxxBridge',
    'DevSupport',
    'RCTActionSheet', #
    'RCTAnimation', #
    'RCTBlob', #
    'RCTCameraRoll', #
    'RCTGeolocation', #
    'RCTImage', #
    'RCTLinkingIOS', #
    'RCTNetwork', #
    'RCTPushNotification', #
    'RCTSettings', #
    'RCTText', #
    'RCTVibration', #
    'RCTWebSocket', #
    'RCTLinkingIOS' #
  ]

  pod 'RNImageCropPicker', :path =>  '../node_modules/react-native-image-crop-picker'
  pod 'react-native-mapbox-gl', :path => '../node_modules/@mapbox/react-native-mapbox-gl'

  # React Native third party dependencies podspecs
  pod 'DoubleConversion', :podspec => "#{rn_path}/third-party-podspecs/DoubleConversion.podspec"
  pod 'glog', :podspec => "#{rn_path}/third-party-podspecs/glog.podspec"

  pod 'react-native-camera', :path => '../node_modules/react-native-camera'

  pod 'react-native-webview', :path => '../node_modules/react-native-webview'

end

# also from https://github.com/ivpusic/react-native-image-crop-picker
post_install do |installer|
  installer.pods_project.targets.each do |target|
    if target.name == "React"
      target.remove_from_project
    end
  end
end
