export const FINAL_PAGE = 'equesteo.FinalPage'
export const FIRST_HORSE_PAGE = 'equesteo.FirstHorsePage'
export const FIRST_HORSE_PHOTO = 'equesteo.FirstHorsePhoto'
export const INTRO_PAGE = 'equesteo.IntroPage'
export const NAME_PAGE = 'equesteo.NamePage'
export const PROFILE_PHOTO_PAGE = 'equesteo.ProfilePhotoPage'
